Ask VK for a bigger photo
SocialiteProviders/VKontakte pull request #24
Opened 2017-04-14 09:48 UTC by bassx1

2017-04-20 15:32 UTC, jhaoda requested changes

2017-04-20 15:32 UTC, jhaoda commented on composer.json
> +    "name": "bassx1/vkontakte",
WTF?

2017-04-20 15:32 UTC, jhaoda commented on composer.json
> -        "socialiteproviders/manager": "~2.0 || ~3.0"
WTF?

2017-04-22 05:31 UTC, faustbrian commented
Yeah no that won't be merged... Changing yourself to the author of the package and removing support for the current version is just... I don't even know.

2017-04-22 05:31 UTC, closed without merging

2017-04-22 07:09 UTC, bassx1 commented
Oh guys, sorry about that, I made it to upload my forked repo to packagist and use it temporarily. 
I wanted to propose only [ first commit](https://github.com/SocialiteProviders/VKontakte/pull/24/commits/ab49b7a66b8c36c463557a668493cc2ab635c61b) for pull request.